### ISSUE TITLE
[Meta] Quiz entity

### ISSUE THREAD

**Issue by and1truong** [atquizz/quizz.module#2]
- https://www.drupal.org/node/2355375
- Old issue: https://github.com/atdrupal/quiz.module/issues/18
## Basic entity
- [x] Define schema
- [x] Make sure quiz support revision
- [x] Define new permissions, callbacks.
- [x] Quiz entity link
- [x] Update quiz & question relationship
  - [x] Rename results.{nid,vid} 
- [x] Missing language column in quiz 
- [ ] Update views integration
## Quiz type entity
- [x] /admin/structure/quiz/add
- [x] /admin/structure/quiz/manage/%quiz_type/edit
- [x] /admin/structure/quiz/manage/%quiz_type/clone
- [x] /admin/structure/quiz/manage/%quiz_type/delete
- [x] /admin/structure/quiz/manage/%quiz_type/export
- [x] /admin/structure/quiz/manage/%quiz_type/fields
- [x] /admin/structure/quiz/manage/%quiz_type/display
- [x] Add QuizType.description 
- [x] Add quiz type description at /quiz/add 
- [x] Add QuizType.help 
- [x] Display quiz type help text when user create new quiz. 
### Quiz entity admin
- [x] /admin/content/quiz
- [ ] Views integration to /admin/content/quiz
  - [x] Created, Changed as date time
  - [x] View, Edit, Delete links 
  - [ ] Add view access checking
### Quiz entity form
- [x] Define form
- [x] Validate
- [x] Submit
  - [x] Save quiz properties
  - [x] Check entity revision options
- [x] Implement hook_field_extra_fields()
- [x] If admin selects "Use the administration theme when editing or creating content" at /admin/appearance, use admin theme for /quiz/\* (admin pages).
- [x] If there's only one quiz type, /quiz/add is a form; If not, it should be a list of quiz type links.
- [x] Edit path for quiz entity should be /quiz/%/edit 
- [x] On submit quiz entity form, redirect to /quiz/% if edit form is non-admin 
- [x] Menu item /quiz/%/edit should be menu local task 
- [x] Delete URL for quiz should be /quiz/%/delete 
- [x] Provide delete link (fake button) for quiz entity form 
- [x] /quiz/%/edit/questions 
- [x] /quiz/%/revisions
- [x] /quiz/%/results 
- [x] /quiz/%/my-results 
- [x] /quiz-result/%
- [x] On delete quiz entity: Delete related content 
- [x] Quiz entity form › Remember as global 
- [x] Quiz entity form › Remember my settings 
### Quiz entity view
- [x] /quiz/%quiz/view 
- [x] Define controller for /quiz/%quiz_entity/take 
- [x] Define controller for /quiz/%quiz_entity/take/%quiz_question 
- [x] Define controller for /quiz/%quiz_entity/take/%quiz_question/feedback 
- [x] Quiz taking navigation 
### Update test cases
- [x]  Quiz Taking 
- [x] Quiz Feedback 
- [x] Quiz navigation/jumping 
- [x] Quiz result 
- [x] Short Answer
- [x] Scale
- [x] Quiz page
- [x] Multichoice
- [x] Matching
- [x] Long Answer
- [x] TrueFalse
### Others
- [x] [Bug] Quiz entity load is not working correctly 
- [x] Define metadata for quiz entity 
- [ ] Correct quiz access checking 
- [x] Update quiz_stats.module to work with quiz entity 
### Migrate
- [x] Implements hook_update_N() to update schema 
- [x] Migrate quiz node to quiz entity 
- [x] Apply path aliases rom quiz nodes to quiz entities 
- [x] Quiz node body -> quiz entity body 
- [x] Clean up migrate data
- [ ] If pathauto is enabled, has pattern for quiz node -> migrate pathauto pattern 
## Related issues
- [x] Add {quiz_user_settings}.nid => type (quiz type)
- [x] Remove 'quiz' entity — Drop {quiz_node_properties} 
- [x] Add redirect node/add/quiz => quiz/add 
- [x] Add body field to all new quiz type
- [x] Custom URI for each quiz type Postponed]
- [ ] Support pathauto module 
- [ ] [Open/Close Date AND Time?](https://www.drupal.org/node/505676)
- [ ] [Quiz doesn't handle daylight savings time](https://www.drupal.org/node/1337758)
- [ ] Question settings per quiz type 
- [x] Change tab title "Edit" to "Settings" at /admin/structure/quiz/manage/quiz 
- [x] What's {quiz_terms}?
- [ ] Get rid of $_SESSION directly usage 
- [ ] Rename {quiz_user_settings}.nid => qid
- [ ] Drop {quiz_user_settings} and related code.
- [ ] Is hook_quiz_view still needed?

**Comment by and1truong** [comment]
https://github.com/atdrupal/quizz.module/wiki/Quiz-entity
