### ISSUE TITLE
[Meta] Question as entity

### ISSUE THREAD

**Issue by and1truong** [atquizz/quizz.module#3]
- [Issue on Drupal.org](https://www.drupal.org/node/2314145)
- [Release blockers](https://www.drupal.org/project/issues/search?issue_tags=7.x-5.0%20release%20blocker)
- Old issue https://github.com/atdrupal/quiz.module/issues/84
- [ ] [Convert Result option to entity](https://www.drupal.org/node/2374285)
## Quiz API changes
- [x] QuestionPlugin::saveRelationships() should accepts quiz ID & VID.
- [x] Move QuizHelper::addQuestion() to QuizEntityContorller::addQuestion()
- [x] Move QuizHelper::updateMaxScoreProperty() to Quiz.ScoreIO::updateTotalScore()
- [x] Fix QuizEntity.QuestionIO.getQuestions()
  - [x] Fix QuizEntity.QuestionIO.getRequiredQuestions()
  - [x] Fix QuizEntity.QuestionIO.buildCategoziedQuestionList()
## Schema change
- [x] quiz_relationship.question_nid => quiz_relationship.question_qid
- [x] quiz_results_answers.question_nid => quiz_results_answers.question_qid
## Quiz Question API changes
- [x] Rename QuestionPlugin::getNodeProperties() -> QuestionPlugin::load()
## Details
- [x] Question type management page
  - [x] Question type add/edit/delete form
  - [x] Question add/edit/delete form
- [x] Render "Add question" link on /admin/content/quiz-questions page.
- [x] /quiz-question/%quiz_question
- [x] /quiz-question/%quiz_question/devel
- [x] On question type module enabled, create new default bundle for question entity
- [x] Define `/quiz-question/add` landing page
- [x] Define question form `/quiz-question/add/%quiz_question_type`
- [x] Auto adding body field to question bundle.
- [x] Implement hook_field_extra_fields()
- [x] Question management page /admin/structure/quiz-questions
  - [x] Add new permission 'administer quiz questions'.
  - [x] Add '%question_type (%plugin_name)' column for /admin/structure/quiz-questions
- [x] Add link to go back to questions management when user view a question
- [x] /quiz-question/%/edit
- [x] /quiz-question/%/delete
- [x] Update quiz_question schema #85 
- [x] Update /quiz/%quiz/questions page
  - [x] User should go back to /quiz/%/questions after create new question.
  - [x] Update  question bank view
    - [x] Bug: Question are not being aware of created/changed properties.
    - [x] Task: Can not make relationship from question -> author
    - [x] Update metadata for question, changed and created properties should be date time.
    - [x] Update quiz_action_info() to make 'add question to quiz' action to work with question entity.
  - [x] Update "Questions in this quiz" fieldset
- [x] Update quiz taking process
- [x] Define new permissions per question bundles
- [x] Update quiz stats module
- [x] Update Generator
- [x] Can not drag question to page — /quiz/%/questions
- [x] Fix permission checking on /quiz-question/add/*
- [x] Disable question types when module disabled.
- [x] Missing language column
- [x] /quiz-question/%/revisions
- [ ] Check `$form['quiz_global_settings']['quiz_index_questions']`
- [ ] Test question permissions
- [ ] quiz-question/add should be an admin path
## Upgrade path
- [x] Convert question node types to question bundles
- [x] Upgrade path test cases
- [ ] Convert question nodes to question entities
- [ ] Role which can manage nodes, they should be granted 'administer quiz questions' on migrate.
## Misc
- [x] Find and fix /node/ -> /quiz-question/
- [x] q_nid -> q_qid
- [x] Find and fix drupalCreateNode
- [x] $question->nid
- [x] "node/$question->nid/edit"
- [x] quiz_question_module_for_type should be a method of QuestionType class.
- [x] Fix field_create_instance() in question type modules — quiz_question_add_body_field()
- [x] Update quiz_load() to make sure $reset param works with $id.
- [x] question_nid -> question_qid
- [x] Remove {quiz_question_properties}
- [x] Find and fix node_build_content()
- [x] Find & fix 'question node'
- [ ] Follow
- [ ] Find and fix 'field_image' — ddlines
- [ ] variable_set('node_options_…
- [ ] Merge commit 844b21d2e07b4f2d7e42f6fa06c9b3fb7c889aa7

**Comment by and1truong** [comment]
https://github.com/atdrupal/quizz.module/wiki/Quiz-entity
